# Generated by Django 5.2.7 on 2025-11-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='language',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Java', 'Java'), ('SQL', 'SQL')], max_length=255, null=True),
        ),
    ]
