# Generated by Django 5.2.7 on 2025-11-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_blogimage_blog_is_draft_alter_blog_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('Full Stack/Software Engineering', 'Full Stack/Software Engineering'), ('ML/Data Science', 'ML/Data Science'), ('Data Analytics', 'Data Analytics'), ('AI', 'AI')], max_length=255, null=True),
        ),
    ]
