# Generated by Django 5.2.7 on 2025-11-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0005_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='web_app_link_1',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Web app link 1'),
        ),
        migrations.AddField(
            model_name='blog',
            name='web_app_link_2',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Web app link 2'),
        ),
        migrations.AddField(
            model_name='blog',
            name='web_app_link_3',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Web app link 3'),
        ),
    ]
